.TH DETECTFS.LANYFS 8 "01-Aug-2012" "lanyfs utils 1.4"
.SH NAME
detectfs.lanyfs - detect a lanyard filesystem (lanyfs)
.SH SYNOPSIS
.B detectfs.lanyfs
\fIdevice\fP
.SH DESCRIPTION
.B detectfs.lanyfs
detects lanyfs on a device. Special file \fIdevice\fP points to the
target device, e.g. \fI/dev/sdXY\fP.
.SH AVAILABILITY
.B detectfs.lanyfs
is part of the lanyfs utils package available from http://www.nonattached.net/lanyfs
.SH AUTHOR
Written by Dan Luedtke <mail@danrl.de>.
